config/routes.rb
Demo::Application.routes.draw do |map|
  resources :users
  resources :posts
  resources :sessions, :only => [:new, :create, :destroy]

  map.home '/', :controller => 'users', :action => 'index'
  match '/signup', :to => 'users#new'
  match '/signin', :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'

end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user

  validates :title, :presence => true
  validates_length_of :title, :maximum => 256
  validates :user_id, :presence => true
end

app/models/user.rb
require 'digest'

class User < ActiveRecord::Base
  attr_accessor :password
  attr_accessible :name, :email, :password, :password_confirmation

  email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :name, :presence => true
  validates :email, 
            :presence => true,
            :uniqueness => true,
            :format => { :with => email_regex }
  validates_length_of :name, :maximum => 64
  validates :password, 
            :presence => true,
            :confirmation => true,
            :length => { :within => 8..40 }

  before_save :encrypt_password

  has_many :posts, :dependent => :destroy

  def password_match?(submitted_password)
    encrypted_password == encrypt(submitted_password)
  end

  def self.authenticate(email, password)
    user = find_by_email(email)
    user && user.password_match?(password) ? user : nil
  end

  def self.authenticate_with_email(id, cookie_email)
    user = find(id) rescue nil
    user && user.email == cookie_email ? user : nil
  end

  private

  def encrypt_password
    self.encrypted_password = encrypt(password)
  end

  def encrypt(string)
    Digest::SHA2.hexdigest(string)
  end
end

app/models/user_observer.rb
class UserObserver < ActiveRecord::Observer
  def after_create(user)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper

  def check_logged_in
    unless sign_in?
      redirect_to signin_path
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :check_logged_in
  before_filter :check_permission, :only => [:edit, :update, :destroy]

  make_resourceful do
    actions :all

    before :create do
      current_object.user_id = current_user.id
    end
  end
  
  private

  def check_permission
    if current_user.id != current_object.user_id
      flash[:error] = 'Permission denied!'
      redirect_to home_path
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.authenticate(params[:session][:email], params[:session][:password])
    if user.nil?
      flash[:error] = "Invalid email/account."
      render :new
    else
      sign_in(user)
      redirect_to user
    end
  end

  def destroy
    sign_out
    redirect_to signin_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :check_logged_in, :except => [:new, :create]
  before_filter :check_permission, :only => [:edit, :update]

  make_resourceful do
    actions :all
  end

  private

  def check_permission
    if current_user.id != current_object.id
      flash[:error] = 'Permission denied!'
      redirect_to home_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def page_title(title)
    content_for :title do
      title
    end
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def sign_in(user)
    cookies.permanent.signed[:remember_token] = [user.id, user.email]
    self.current_user = user
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    @current_user ||= user_from_remember_token
  end

  def sign_out
    self.current_user = nil
    cookies.delete(:remember_token)
  end

  def sign_in?
    !current_user.nil?
  end

  private

  def user_from_remember_token
    User.authenticate_with_email(*remember_token)
  end

  def remember_token
    cookies.signed[:remember_token] || [nil, nil]
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_menu.html.erb
<% if sign_in? %>
  <%= link_to 'Users', users_path %> | 
  <%= link_to 'Posts', posts_path %> | 
  <%= link_to(current_user.name, current_user)  %> | 
  <%= link_to('Sign out', signout_path)  %>
<%- end -%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Demo | <%= yield :title %></title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>
  <div id="menu">
    <%= render :partial => 'layouts/menu' %>
  </div>

<%= yield %>

</body>
</html>

app/views/posts/_form.html.erb
<% form_for @post, :html => { :class => 'form' } do |f| %>
  <%= error_messages_for :post %>
  <div class="fields">
    <%= f.label :title %>
    <br/>
    <%= f.text_field :title, :class => 'text' %>
  </div>
  <div class="fields">
    <%= f.label :content %>
    <br/>
    <%= f.text_area :content, :class => 'text' %>
  </div>
  <br/>
  <%= f.submit "Save", :class => 'submit' %>
<% end %>

app/views/posts/edit.html.erb
<%= page_title("Edit Post") %>
<h2>Edit Post</h2>
<%= render :partial => 'form' %>
<br/>
<%= link_to 'Show', current_object %>

app/views/posts/index.html.erb
<% page_title("List of Posts") %>
<%- unless flash[:error].nil? -%>
  <div class="error"><%= flash[:error] %></div>
<%- end -%>
<h2>List of Posts</h2>
<table width="100%">
  <tr>
    <td>Title</td>
    <td>Posted by</td>
    <td>Content</td>
  </tr>
  <%- current_objects.each do |p| -%>
    <tr>
      <td width="20%"><%= link_to p.title, p %></td>
      <td width="20%"><%= link_to p.user.name, p.user %></td>
      <td><%= p.content %></td>
    </tr>
  <%- end -%>
</table>
<br/>
<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<% page_title("New post") %>
<h2>New Post</h2>
<%= render :partial => 'form' %>

app/views/posts/show.html.erb
<% page_title("Post") %>
<h2>Post Detail</h2>
<table width="100%">
  <tr>
    <td width="10%">Title:</td>
    <td><%=h current_object.title %></td>
  </tr>
  <tr>
    <td>Content:</td>
    <td><%=h current_object.content %></td>
  </tr>
  <tr>
    <td>By:</td>
    <td><%= link_to current_object.user.name, current_object.user %></td>
  </tr>
  <tr>
    <td>On:</td>
    <td><%= current_object.created_at %></td>
  </tr>
</table>
<br/>
<%= link_to 'Edit', edit_post_path(current_object) %>
<br/>
<%= link_to 'Delete', post_path(current_object), :method => :delete, :confirm => 'Are you sure' %>
<br/>
<%= link_to 'New Post', new_post_path %>

app/views/users/_form.html.erb
<% form_for @user, :html => { :class => 'form' } do |f| -%>
  <%= error_messages_for :user %>
  <div class="fields">
    <%= f.label :name %>
    <br/>
    <%= f.text_field :name, :class => 'text' %>
  </div>
  <div class="fields">
    <%= f.label :email %>
    <br/>
    <%= f.text_field :email, :class => 'text' %>
  </div>
  <div class="fields">
    <%= f.label :password %>
    <br/>
    <%= f.password_field :password, :class => 'text' %>
  </div>
  <div class="fields">
    <%= f.label :password_confirmation %>
    <br/>
    <%= f.password_field :password_confirmation, :class => 'text' %>
  </div>
  <%= f.submit "Submit", :class => 'submit' %> 
  <%- unless sign_in? -%>
    or <%= link_to 'Sign In', signin_path %>
  <%- end -%>
<%- end -%>

app/views/users/edit.html.erb
<%= page_title("Edit User") %>
<h2>Edit User</h2>
<%= render :partial => 'form' %>
<br/>
<%= link_to 'Show', current_object %>

app/views/users/index.html.erb
<% page_title("List of Users") %>
<%- unless flash[:error].nil? -%>
  <div class="error"><%= flash[:error] %></div>
<%- end -%>
<h2>List of Users</h2>
<table width="100%">
  <tr>
    <td>Name</td>
    <td>Email</td>
  </tr>
  <%- current_objects.each do |u| -%>
    <tr>
      <td width="50%"><%= link_to u.name, u %></td>
      <td><%= u.email %></td>
    </tr>
  <%- end -%>
</table>

app/views/users/new.html.erb
<% page_title("New user") %>
<h2>Sign up to Demo</h2>
<%= render :partial => 'form' %>

app/views/users/show.html.erb
<% page_title("User #{current_object.name}") %>
<h2>Account Information</h2>
Name: <%= current_object.name %>
<br/>
Email: <%= current_object.email %>
<br/>
<br/>
<%= link_to 'Edit', edit_user_path(current_object) %>
<br/>
<h3>Posts</h3>
<table width="100%">
  <tr>
    <td>Title</td>
    <td>Content</td>
  </tr>
  <%- current_object.posts.each do |p| -%>
    <tr>
      <td width="20%"><%= link_to p.title, p %></td>
      <td><%= p.content %></td>
    </tr>
  <%- end -%>
</table>
<br/>